---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taiga-secrets
  namespace: taiga
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: taiga-secrets
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .db_user }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
        POSTGRES_DB: "{{ .db_name }}"
        POSTGRES_HOST: "{{ .db_host }}"
        TAIGA_SECRET_KEY: "{{ .secret_key }}"
        RABBITMQ_USER: "{{ .rabbitmq_user }}"
        RABBITMQ_PASS: "{{ .rabbitmq_pass }}"
  data:
    - secretKey: db_user
      remoteRef:
        key: secret/data/kubernetes/taiga/database
        property: username
    - secretKey: db_password
      remoteRef:
        key: secret/data/kubernetes/taiga/database
        property: password
    - secretKey: db_name
      remoteRef:
        key: secret/data/kubernetes/taiga/database
        property: database
    - secretKey: db_host
      remoteRef:
        key: secret/data/kubernetes/taiga/database
        property: host
    - secretKey: secret_key
      remoteRef:
        key: secret/data/kubernetes/taiga/app
        property: secret_key
    - secretKey: rabbitmq_user
      remoteRef:
        key: secret/data/kubernetes/taiga/rabbitmq
        property: username
    - secretKey: rabbitmq_pass
      remoteRef:
        key: secret/data/kubernetes/taiga/rabbitmq
        property: password
