---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - rabbitmq.yaml
  - taiga-back.yaml
  - taiga-async.yaml
  - taiga-events.yaml
  - taiga-protected.yaml
  - taiga-front.yaml
  - ingress.yaml
