apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@bsdserver.nl
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.bsdserver.nl
            solverName: transip
            config:
              accountName: pderuiter
              ttl: 300
              privateKeySecretRef:
                name: transip-credentials
                key: private.key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: admin@bsdserver.nl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.bsdserver.nl
            solverName: transip
            config:
              accountName: pderuiter
              ttl: 300
              privateKeySecretRef:
                name: transip-credentials
                key: private.key
