apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transip-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: transip-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dns
        property: transip_login
    - secretKey: privateKey
      remoteRef:
        key: dns
        property: transip_private_key
