---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-database
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sonarqube-database
    creationPolicy: Owner
  data:
    - secretKey: SONAR_JDBC_URL
      remoteRef:
        key: secret/kubernetes/sonarqube/database
        property: SONAR_JDBC_URL
    - secretKey: SONAR_JDBC_USERNAME
      remoteRef:
        key: secret/kubernetes/sonarqube/database
        property: SONAR_JDBC_USERNAME
    - secretKey: SONAR_JDBC_PASSWORD
      remoteRef:
        key: secret/kubernetes/sonarqube/database
        property: SONAR_JDBC_PASSWORD
