---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phpipam-database
  namespace: phpipam
  labels:
    app.kubernetes.io/name: phpipam
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: phpipam-database
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: secret/kubernetes/phpipam/database
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: secret/kubernetes/phpipam/database
        property: MYSQL_DATABASE
    - secretKey: MYSQL_USER
      remoteRef:
        key: secret/kubernetes/phpipam/database
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: secret/kubernetes/phpipam/database
        property: MYSQL_PASSWORD
