apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - minio-setup-job.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - maintenance-cronjob.yaml
  - pooler.yaml
  - podmonitor.yaml
  - prometheusrules.yaml
  - grafana-dashboard.yaml
