apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-check
  namespace: web-check
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: 192.168.2.160
  labels:
    app.kubernetes.io/name: web-check
spec:
  ingressClassName: traefik
  rules:
    - host: webcheck.bsdserver.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-check
                port:
                  name: http
  tls:
    - hosts:
        - webcheck.bsdserver.nl
      secretName: web-check-tls
