apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-tuning
  - sealed-secrets
  - vault-unseal
  - external-secrets
  - metallb
  - traefik
  - cert-manager
  - external-dns
  - external-dns-transip
  - longhorn
  - cloudnative-pg
  - minio
  - observability
  - searxng
  - homepage
  - bytestash
  - web-check
