apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-tuning
  - sealed-secrets
  - external-secrets
  - metallb
  - traefik
  - cert-manager
  - external-dns
  - longhorn
  - minio
  - observability
  - searxng
