apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-docker
  namespace: nexus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Allow large image layers
    traefik.ingress.kubernetes.io/buffering.maxRequestBodyBytes: "0"
    traefik.ingress.kubernetes.io/buffering.maxResponseBodyBytes: "0"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - docker.nexus.bsdserver.nl
      secretName: nexus-docker-tls
  rules:
    - host: docker.nexus.bsdserver.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8082
