apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepositories.yaml
  - externalsecrets.yaml
  - prometheus-helmrelease.yaml
  - loki-helmrelease.yaml
  - alloy-helmrelease.yaml
  - grafana-helmrelease.yaml
  - keycloak-dashboard-configmap.yaml
  - minio-dashboard-configmap.yaml
  - pangolin-dashboard-configmap.yaml
  - traefik-dashboard-configmap.yaml
  - ntfy-helmrelease.yaml
