---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-database
    creationPolicy: Owner
  data:
    - secretKey: KC_DB_URL_HOST
      remoteRef:
        key: secret/kubernetes/keycloak/database
        property: KC_DB_URL_HOST
    - secretKey: KC_DB_URL_PORT
      remoteRef:
        key: secret/kubernetes/keycloak/database
        property: KC_DB_URL_PORT
    - secretKey: KC_DB_URL_DATABASE
      remoteRef:
        key: secret/kubernetes/keycloak/database
        property: KC_DB_URL_DATABASE
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: secret/kubernetes/keycloak/database
        property: KC_DB_USERNAME
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: secret/kubernetes/keycloak/database
        property: KC_DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: secret/kubernetes/keycloak/admin
        property: KEYCLOAK_ADMIN
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/kubernetes/keycloak/admin
        property: KEYCLOAK_ADMIN_PASSWORD
