apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - keycloak.yaml
  - ingress.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: keycloak-realm-import
    files:
      - master-realm.json
generatorOptions:
  disableNameSuffixHash: true
