apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-auth
  # Phase 2 - uncomment after ESO is working
  # - metallb
  # Phase 3 - uncomment after MetalLB/Traefik are working
  # - cert-manager
  # - external-dns
