apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-auth
  - metallb
  - cert-manager
  - external-dns
  - databases
  - ghost
  - homelab-dashboard
  - listmonk
  - taiga
