apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bytestash
  namespace: bytestash
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: 192.168.2.160
  labels:
    app.kubernetes.io/name: bytestash
spec:
  ingressClassName: traefik
  rules:
    - host: snippets.bsdserver.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bytestash
                port:
                  name: http
  tls:
    - hosts:
        - snippets.bsdserver.nl
      secretName: bytestash-tls
